name: VidaXL to Matrixify Sync

on:
  schedule:
    # Kører hver time
    - cron: '0 * * * *'
  workflow_dispatch: # Tillader manuel kørsel

jobs:
  sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        pip install requests
    
    - name: Run transform script
      run: |
        python transform_vidaxl.py
    
    - name: Upload CSV as artifact
      uses: actions/upload-artifact@v3
      with:
        name: matrixify-update
        path: matrixify_update.csv
        retention-days: 1
    
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: sync-${{ github.run_number }}
        release_name: Sync ${{ github.run_number }}
        draft: false
        prerelease: false
    
    - name: Upload CSV to Release
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./matrixify_update.csv
        asset_name: matrixify_update.csv
        asset_content_type: text/csv
