name: TEST - Shopify Sync (100 products)

on:
  workflow_dispatch:  # Kun manuel kørsel

jobs:
  test-sync:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    
    - name: Test Shopify sync
      env:
        SHOPIFY_ACCESS_TOKEN: ${{ secrets.SHOPIFY_ACCESS_TOKEN }}
      run: |
        echo "🧪 Running TEST sync with 100 products only"
        python sync_to_shopify_bulk.py
    
    - name: Commit report
      if: always()  # Kør altid, selv hvis sync fejler
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add reports/ || echo "No reports folder"
        git diff --staged --quiet || git commit -m "Add update report - $(date +'%Y-%m-%d %H:%M')"
        git push || echo "No changes to push"
